#!/bin/bash
#
# Install a full Chef cookbook development toolchain
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/chef-utensils
CONFIG_DIR=/etc/chef
USAGE="usage: $0 [-v validation_key] ([-o organization] || [-u url])"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

validation_key=
organization=
chef_url=

while getopts o:u:v: opt
do
    case "$opt" in
      v)  validation_key="${OPTARG}";;
      o)  organization="${OPTARG}"; chef_url="https://api.opscode.com/organizations/${OPTARG}";;
      u)  chef_url="${OPTARG}";;
      \?)   # unknown flag
          echo >&2 ${USAGE}
    exit 1;;
    esac
done
shift `expr ${OPTIND} - 1`

if [ "" != "$chef_url" ]; then
  mkdir -p ${CONFIG_DIR} || error_exit "Cannot create ${CONFIG_DIR}!"
  (
  cat <<'EOP'
log_level :info
log_location STDOUT
EOP
  ) > ${CONFIG_DIR}/knife.rb
  if [ "" != "$chef_url" ]; then
    echo "chef_server_url '${chef_url}'" >> ${CONFIG_DIR}/knife.rb
  fi
  if [ "" != "$organization" ]; then
    echo "validation_client_name '${organization}-validator'" >> ${CONFIG_DIR}/knife.rb
  fi
  chmod 644 ${CONFIG_DIR}/knife.rb
fi

if [ "" != "$validation_key" ]; then
  cp ${validation_key} ${CONFIG_DIR}/validation.pem || error_exit "Cannot copy the validation key!"
  chmod 600 ${CONFIG_DIR}/validation.pem
fi

# rm -f before ln -sf is required for solaris 9
rm -f /usr/bin/chef-client
rm -f /usr/bin/chef-solo
rm -f /usr/bin/chef-apply
rm -f /usr/bin/chef-shell
rm -f /usr/bin/knife
rm -f /usr/bin/shef
rm -f /usr/bin/ohai
rm -f /usr/bin/berks
rm -f /usr/bin/foodcritic
rm -f /usr/bin/kitchen

ln -sf $INSTALLER_DIR/bin/chef-client /usr/bin || error_exit "Cannot link chef-client to /usr/bin"
ln -sf $INSTALLER_DIR/bin/chef-solo /usr/bin || error_exit "Cannot link chef-solo to /usr/bin"
ln -sf $INSTALLER_DIR/bin/chef-apply /usr/bin || error_exit "Cannot link chef-apply to /usr/bin"
ln -sf $INSTALLER_DIR/bin/chef-shell /usr/bin || error_exit "Cannot link chef-shell to /usr/bin"
ln -sf $INSTALLER_DIR/bin/knife /usr/bin || error_exit "Cannot link knife to /usr/bin"
ln -sf $INSTALLER_DIR/bin/shef /usr/bin || error_exit "Cannot link shef to /usr/bin"
ln -sf $INSTALLER_DIR/bin/ohai /usr/bin || error_exit "Cannot link ohai to /usr/bin"

ln -sf $INSTALLER_DIR/bin/berks /usr/bin || error_exit "Cannot link berks to /usr/bin"
ln -sf $INSTALLER_DIR/bin/foodcritic /usr/bin || error_exit "Cannot link foodcritic to /usr/bin"
ln -sf $INSTALLER_DIR/bin/kitchen /usr/bin || error_exit "Cannot link kitchen to /usr/bin"

echo "Thank you for installing Chef Utensils...happy cooking!"

exit 0
